build:
  environment:
    php:
      version: '7.2'
  nodes:
    analysis:
      project_setup:
        override:
        - 'true'
      tests:
        override:
        - php-scrutinizer-run
        - command: phpcs-run
          use_website_config: true
    tests: true
filter:
  excluded_paths:
  - '3rd/*'
  dependency_paths:
  - 'vendor/*'
  - '3rd/httpclient/http.php'
  - '3rd/oauth-api/oauth_client.php'
checks:
  php: true
coding_style:
  php:
    indentation:
      general:
        use_tabs: true
    spaces:
      around_operators:
        relational: false
        multiplicative: false