build:
  environment:
    php:
      version: '7.2'
  nodes:
    analysis:
      project_setup:
        override:
        - 'true'
      tests:
        override:
        - php-scrutinizer-run --enable-security-analysis
        - command: phpcs-run
    tests: true
filter:
  excluded_paths:
  - '3rd/*'
  dependency_paths:
  - 'vendor/*'
checks:
  php: true
coding_style:
  php:
    indentation:
      general:
        use_tabs: true
    spaces:
      around_operators:
        relational: false
        multiplicative: false