<?php
/**
 * Copyright (c) 2019 JOOservices Ltd
 * @author Viet Vu <jooservices@gmail.com>
 * @license GPL
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 */

namespace XGallery\Applications\Cli\Commands\Photos;

use Doctrine\DBAL\DBALException;
use Doctrine\DBAL\FetchMode;
use Gumlet\ImageResize;
use ReflectionException;
use Symfony\Component\Process\Process;
use XGallery\Applications\Cli\Commands\AbstractCommandPhotos;
use XGallery\Defines\DefinesFlickr;
use XGallery\Exceptions\Exception;

/**
 * Class FlickrResizes
 * @package XGallery\Applications\Cli\Commands\Photos
 */
class FlickrResizes extends AbstractCommandPhotos
{
    /**
     * @var array
     */
    protected $photos;

    /**
     * @throws ReflectionException
     */
    protected function configure()
    {
        $this->options = [
            'nsid' => [
                'description' => '',
                'default' => null,
            ],
            'limit' => [
                'default' => DefinesFlickr::RESIZE_LIMIT,
            ],
            'width' => [
                'description' => 'Resize width',
                'default' => 1920,
            ],
            'height' => [
                'description' => 'Resize height',
                'default' => 1080,
            ],
            'position' => [
                'description' => '1: Top; 2: Center; 3: Bottom; 4: Left; 5: Right',
                'default' => ImageResize::CROPCENTER,
            ],
        ];

        parent::configure(); // TODO: Change the autogenerated stub
    }

    /**
     * @return boolean
     * @throws DBALException
     */
    protected function prepare()
    {
        parent::prepare();

        if (!$this->getPhotos()) {
            return false;
        }

        return true;
    }

    /**
     * @param array $steps
     * @return boolean
     */
    protected function process($steps = [])
    {
        return parent::process(
            [
                'resize',
            ]
        );
    }

    /**
     * @return boolean
     */
    protected function resize()
    {
        if (!$this->photos || empty($this->photos)) {
            return false;
        }

        foreach ($this->photos as $photo) {
            $this->info('Process '.$photo->id);
            $process = new Process(
                ['php', 'cli.php', 'photos:flickrresize', '--photo_id='.$photo->id]
            );
            $process->start();
            $process->wait();

            $this->info('Process completed: '.$photo->id);
            $this->progressBar->advance();
        }

        return true;
    }

    /**
     * @return boolean
     * @throws DBALException
     */
    protected function getPhotos()
    {
        $nsid = $this->input->getOption('nsid');

        if (!$nsid) {
            $this->logNotice('No NSID provided');

            return false;
        }

        try {

            $query = ' SELECT `id`, `owner`, `params`'.'  FROM `xgallery_flickr_photos`'
                .' WHERE `owner` = ?'
                .' LIMIT '.$this->input->getOption('limit');

            $this->photos = $this->connection->executeQuery($query, [$nsid])
                ->fetchAll(FetchMode::STANDARD_OBJECT);

            if (!$this->photos || empty($this->photos)) {
                $this->logNotice('There are no photos');

                return false;
            }

            $this->info('Found: '.count($this->photos).' photos', [], true);

            return true;

        } catch (Exception $exception) {

            $this->logError($exception->getMessage());
        }

        return false;
    }
}